apiVersion: v1
kind: Service
metadata:
  name: trend-service
spec:
  type: LoadBalancer    # Use NodePort if cluster not in cloud
  selector:
    app: trend
  ports:
    - protocol: TCP
      port: 80          # External service port
      targetPort: 80    # Pod port
